### ISSUE TITLE
Field have underscore

### ISSUE THREAD

**Issue by vinhxike** [timmolter/Yank#15]
I have table structure:

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) DEFAULT NULL,
  `loginname` varchar(100) NOT NULL,
  `password` varchar(45) NOT NULL,
  `password_salt` varchar(10) NOT NULL,
  `display_name` varchar(100) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `created_time` int(10) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `loginname_UNIQUE` (`loginname`),
  KEY `fk_users_users_idx` (`admin_id`),
  CONSTRAINT `fk_users_users` FOREIGN KEY (`admin_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

Can not get values of fields have underscore:

Users{userId=0, adminId=0, loginname='vinh.vo@8gio.vn', password='1c1802e725674705f25af1de5a50dec9', passwordSalt='null', displayName='null', firstName='null', lastName='null', email='vinh.vo@8gio.vn', phone='0989831911', createdTime=0, active=1}

**Comment by eepstein** [comment]
How about a setting that changes between snake-case (db names) and camel-case (Java) ?

**Comment by timmolter** [comment]
Actually this looks pretty easy with annotations. DBUtils allows for an override map so something like the following would work with an annotation parser beforehand:

    final Map<String, String> columnToPropertyOverrides = new HashMap<>();
    columnToPropertyOverrides.put("WIND_DIRECTION", "WindDirection");
                   
    BeanProcessor dateForProcessor = new BeanProcessor(columnToPropertyOverrides);
    BasicRowProcessor rp = new BasicRowProcessor(dateForProcessor);

**Comment by timmolter** [comment]
@vinhxike This should work fine now. I added the feature and tested it.

**Comment by eepstein** [comment]
cool beans
