### ISSUE TITLE
Allow any datasource to be used.

### ISSUE THREAD

**Issue by timmolter** [timmolter/Yank#21]
Idea: take a look at how Tomcat accepts any datasource and shuts it down properly.

**Comment by timmolter** [comment]
From @eepstein 

Here’s part of a Java 1.5 Generics way to support other DataSources and also the release() functionality:

	public final class YankPoolManager<T extends DataSource & Closeable> {
        …
           private final Map<String, T> pools = ...
        ...
           protected void addDataSource(String name, T ds) {
              pools.put(name, ds);
           }

and then, inside #release() call close() inside a try block.

**Comment by timmolter** [comment]
Of the following connection pools, only Hikari and BoneCP implement `Closeable`.

| JDBC Connection Pool | Implements | methods |
|---|---|
|Hikari|DataSource, Closeable|close(),shutdown()|
|BoneCP|DataSource, Closeable|close(),shutdown()|
|C3P0|DataSource|close()|
|DBCP|DataSource|close()|
|ViburCP|DataSource|terminate()|

**Comment by eepstein** [comment]
2 out of 5 . .. not bad ;-)

Bummer is that 4 of the 5 implement close() but don’t declare the interface.  Fall-back would be dynamic dispatch via something like javassist with introspection, which is what Hikari does for calls to the underlying DataSource…  but seems like a hassle.  The nice thing about doing the generic is it leaves the door open to anyone who wants to write such a wrapper / delegation - whether implemented via dynamic dispatch or long-hand.  And it makes the coupling to the CP looser.

But still, less coverage than getting all 5 of those, which would be ideal.

**Comment by eepstein** [comment]
hmm.   The Java-8 approach I’d take would be to include an optional “closer” Function in the addConnectionPool() method.  Default (null) would cast to closable and call close(), but if caller provided a closer function the release method would invoke that.  This is fully general then, but with lambda’s required an Interface and someone to implement for each CP type they want to use.  That said, the Interface in this case has 1 method, so unlike wrapping and delegating this is lightweight and goes general purpose….  Works , but is clearly a work-around.  That said, if you think that fits, then it’s light-weight on the coding side.  So, if yes, lemme know if you want me to code that.

**Comment by timmolter** [comment]
Nah, using the default Hikari is simple and effective for the purpose of this lib.
