### ISSUE TITLE
queryColumnSQLKey is not working as intended

### ISSUE THREAD

**Issue by lakshmisri** [timmolter/Yank#25]
When I use the queryColumn, it give me the desired result whereas using queryColumnSQLKey and passing the SQL key does not work well. It returns empty value for each record and not the actual value.

**Comment by timmolter** [comment]
Thanks for reporting that. I fixed it and the 3.0.1 snapshot jar is here: https://oss.sonatype.org/content/groups/public/com/xeiam/yank/3.0.1-SNAPSHOT/

I'll push a 3.0.1 release soon.

**Comment by lakshmisri** [comment]
Sure thanks.

On Monday, April 27, 2015, Tim Molter <notifications@github.com> wrote:

> Thanks for reporting that. I fixed it and the 3.0.1 snapshot jar is here:
> https://oss.sonatype.org/content/groups/public/com/xeiam/yank/3.0.1-SNAPSHOT/
>
> I'll push a 3.0.1 release soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timmolter/Yank/issues/25#issuecomment-96682289>.
>


-- 
Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Hello,

When I use the method queryBeanListSQLKey, its not mapping all the values
of the column. For e.g., I have a column called spotfix_id in the database
and have a getter and setter with the same name. Not sure why it doesnt
map.. Can you help?

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

On Mon, Apr 27, 2015 at 8:48 PM, Lakshmisri Gopalan <lakshmisri@ideas2it.com
> wrote:

> Sure thanks.
>
>

**Comment by timmolter** [comment]
It should be mapping. Can you paste you setter method here?

**Comment by lakshmisri** [comment]
/**
 * @return the spotfix_id
 */
public Long getSpotfix_id() {
return spotfix_id;
}

/**
 * @param spotfix_id the spotfix_id to set
 */
public void setSpotfix_id(long spotfix_id) {
this.spotfix_id = spotfix_id;
}

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Does it sound correct?

How do I inject a class object to Sundial job

On Monday, April 27, 2015, Lakshmisri Gopalan <lakshmisri@ideas2it.com>
wrote:

> /**
>  * @return the spotfix_id
>  */
> public Long getSpotfix_id() {
> return spotfix_id;
> }
>
> /**
>  * @param spotfix_id the spotfix_id to set
>  */
> public void setSpotfix_id(long spotfix_id) {
> this.spotfix_id = spotfix_id;
> }
>
> Regards,
> Lakshmisri Gopalan
> IDEAS2IT Technologies
>
> On Mon, Apr 27, 2015 at 11:36 PM, Tim Molter <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> It should be mapping. Can you paste you setter method here?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/timmolter/Yank/issues/25#issuecomment-96762377>.
>>
>
>

-- 
Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
See: https://github.com/timmolter/Yank/blob/develop/src/test/java/com/xeiam/yank/SnakeCaseTest2.java

I made a test class for you demonstrating your specific example and it works fine.

**Comment by timmolter** [comment]
If you want help with Sundial open an issue on the Sundial github repo with a specific question and sufficient details.

**Comment by lakshmisri** [comment]
Yup done.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies
