### ISSUE TITLE
Connection Pooling issue

### ISSUE THREAD

**Issue by lakshmisri** [timmolter/Yank#26]
Hi,

I have used Yank manager for my database connection but beyond a point of time, I am getting "Too many connections". Do I need to handle separately for connection pooling.

**Comment by timmolter** [comment]
Thanks for reporting the issue. I've never seen that before. Can you paste the entire message here?

**Comment by lakshmisri** [comment]
I am using Sundial and Yank for scheduling jobs. I have about 2 batch jobs
and they are scheduled to be executed every 5 min. THe connection
properties that I have used are

jdbcUrl=jdbc:mysql://localhost/localDB
username=root
password=
maximumPoolSize=20


DEBUG  [00:25:02.788] [HikariCP connection filler (pool HikariPool-0)]
c.z.h.p.PoolUtilities -  Closing connection null
DEBUG  [00:25:02.789] [HikariCP connection filler (pool HikariPool-0)]
c.z.h.p.HikariPool -  Connection attempt to database HikariPool-0 failed:
Data source rejected establishment of connection,  message from server:
"Too many connections"
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data
source rejected establishment of connection,  message from server: "Too
many connections"
at sun.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
~[na:na]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown
Source) ~[na:1.8.0_51]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_51]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.Util.getInstance(Util.java:386)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1114)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2493)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at
com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2526)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2311)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at sun.reflect.GeneratedConstructorAccessor57.newInstance(Unknown Source)
~[na:na]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown
Source) ~[na:1.8.0_51]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_51]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at
com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:83)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:89)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at
com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:409)
~[cleanIndiaService-0.8.0.jar:0.8.0]
at com.zaxxer.hikari.pool.HikariPool$1AddConnection.run(HikariPool.java:78)
[cleanIndiaService-0.8.0.jar:0.8.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[na:1.8.0_51]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[na:1.8.0_51]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
I have just two batch jobs. Assuming one connection per job, it should go
 back to the pool. That is my assumption and I have not handled anything
explicitly to return the connection object to the pool.

Regards,
Lakshmisri Gopalan


On Tue, Aug 25, 2015 at 2:27 AM, Lakshmisri Gopalan <lakshmisri@ideas2it.com

**Comment by lakshmisri** [comment]
Hi.. I think you need to upgrade your Hikari jar to higher version. Looks that they have fixed this issue in 2.3.7 onwards. I am using Yank with jdk 7. So they have a stable release yesterday which is 2.4.1

**Comment by timmolter** [comment]
@lakshmisri Thanks for the suggestion. I updated the Hikari jar. Can you please try out the latest Yank snapshot jar?

BTW, I will probably update Yank to Java 7 soon and at that time bump up to the Hikari 2.4.x jar.

**Comment by lakshmisri** [comment]
Yeah that will be fine. I am using Java 7 but still your Yank is working
good :)

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
Can you confirm that the problem has now been definitely solved?

**Comment by lakshmisri** [comment]
I have shared a link in the previous comment.  Could you take a look at
that?  I have also emailed the other team asking for the Java 6 stable
version.

On Tuesday, August 25, 2015, Tim Molter <notifications@github.com> wrote:

> Can you confirm that the problem has now been definitely solved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timmolter/Yank/issues/26#issuecomment-134554988>.
>


-- 
Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Hi,
the pom.xml does not have the latest jar version, it still shows 2.3.6 but has to be 2.3.9

https://github.com/brettwooldridge/HikariCP

**Comment by timmolter** [comment]
Thanks, I made a mistake. Try now as it should be working.

**Comment by lakshmisri** [comment]
For some reason, its not downloading the dependancy. Does it take some time
for the dependancy to get reflected in maven?

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

On Tue, Aug 25, 2015 at 9:32 PM, Lakshmisri Gopalan <lakshmisri@ideas2it.com
> wrote:

> I have shared a link in the previous comment.  Could you take a look at
> that?  I have also emailed the other team asking for the Java 6 stable
> version.
>

**Comment by timmolter** [comment]
The dependency is there: https://oss.sonatype.org/content/groups/public/com/xeiam/yank/3.0.2-SNAPSHOT/

You're aware that it's a snapshot jar, right?

**Comment by lakshmisri** [comment]
I am using 3.0.1 and not snapshot..

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
You need to use 3.0.2-SNAPSHOT for the latest changes

**Comment by timmolter** [comment]
Read the README file for more info.

**Comment by lakshmisri** [comment]
Is this a stable version?

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
No, it's a snapshot version. I'll release a stable version after I know it's tested and the problem is fixed.

**Comment by lakshmisri** [comment]
I have put that in my code. Give me a day or two. I will monitor that and
let you know .

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
Thanks much. I hope it solves the issue!

**Comment by lakshmisri** [comment]
Even if i use the snapshot jar, it is not referring to the new hikari jar

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
That's hard to believe. Are you sure you're using 3.0.2-SNAPSHOT and not  3.0.1-SNAPSHOT ?

**Comment by timmolter** [comment]
It should be referring to 2.3.9

**Comment by lakshmisri** [comment]
Which one to use.  Ur read me said 3.0.2 snapshot

On Wednesday, August 26, 2015, Tim Molter <notifications@github.com> wrote:

> It should be referring to 2.3.9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timmolter/Yank/issues/26#issuecomment-135115883>.
>


-- 
Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
Yank 3.0.2-SNAPSHOT

which depends on hikariCP-java6 2.3.9

**Comment by lakshmisri** [comment]
That is what I have referred to but its not referring to the new one.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
You probably have a maven issue. If I look at the deployed snapshot jar on Sonatype, the pom is correct, showing the appropriate Hikari dependency.

![screen shot 2015-08-27 at 8 33 56 am](https://cloud.githubusercontent.com/assets/738972/9514037/992a71b0-4c96-11e5-8b55-16899739d6ac.png)

**Comment by lakshmisri** [comment]
Ok it is fine now. I will monitor until end of day today and let you know
if I see any connection pooling issues.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Hello,

its about 1.5 days and looks there I am not getting that issue anymore.

Regards,
Lakshmi

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Hello Tim,

so far no issues and the code is deployed, up and running without issues
for over three days.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by timmolter** [comment]
That's great! Thank you very much for testing that our for me and reporting back. I'll release a stable jar within the week some time.

**Comment by lakshmisri** [comment]
Sure. Could you let me know when you are done so that I can switch over.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

**Comment by lakshmisri** [comment]
Have you made a release?

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies

On Mon, Aug 31, 2015 at 3:22 PM, Lakshmisri Gopalan <lakshmisri@ideas2it.com

**Comment by timmolter** [comment]
No. I'll try to get it this weekend.

~Tim

**Comment by timmolter** [comment]
It's now on Maven Central 3.0.2

**Comment by lakshmisri** [comment]
Thanks Tim. I will also change my configuration.

Regards,
Lakshmisri Gopalan
IDEAS2IT Technologies
