### ISSUE TITLE
where is the poolname in the new version?

### ISSUE THREAD

**Issue by solinad21** [timmolter/Yank#28]
i have a properties file with various databases differentiated by pool name,
how can i manage this in the new version?

**Comment by timmolter** [comment]
Sorry, that was removed at version 3.0.0.

**Comment by solinad21** [comment]
thanks for your answer, 

in the version 3 are there a strategy for manage multiple connections?

is essential for my app this feature.

**Comment by solinad21** [comment]
are there problems if i am using yank + spring mvc ?

**Comment by timmolter** [comment]
No, sorry, there is no way to have separate connection pools any more.
