### ISSUE TITLE
concurrent, multiuser and custom database

### ISSUE THREAD

**Issue by solinad21** [timmolter/Yank#29]
apologies if I am repetitive,

I have a concurrent, multiuser web application that each user connects to this application uses a custom database.

eg User 1 connects to the database 1 and so on (I have almost 100 users and the same number of databases).

several or all users are connected simultaneously.

yank 3 can optimally cover this scenario?

otherwise you could please recommend some strategy or other product (excuse me if the latter is reckless)

**Comment by timmolter** [comment]
I'm thinking about how I can add that functionality back in in an elegant manner. More later...

**Comment by timmolter** [comment]
OK, I added functionality for this in the latest snapshot release.
